### PR TITLE
Fix multiple download and browse while downloading

### LINKED ISSUE #744: Can download only one file at a time / cannot browse while downloading
I can only download one file at a time. If I download a file, I can't browse tinyfilemanager anymore. If I try to click anywhere while downloading a file (or if I try to download a second file), the action will be queued until the download finishes. However, if I start a new private window while downloading a file, I can simultaneously download another file/browse tinyfilemanager. That's why I think this may be related to session management. See:
https://stackoverflow.com/questions/1610168/downloading-files-with-php-only-downloading-one-at-a-time

### PR DESCRIPTION
**Pull request by vadasziattila**
this change resolves #744 by adding the option to able to download multiple files and browse while downloading.
Signed-off-by: Vadászi Attila <vadaszi.attila@bitecode.hu>

### CODE REVIEW

**Review by prasathmani — APPROVED** [review]

File: tinyfilemanager.php [hunk 1]
```diff
@@ -2225,6 +2309,8 @@ class="edit-file"><i class="fa fa-pencil-square-o"></i> <?php echo lng('Advanced
                 <li class="list-inline-item"> <a href="#/select-all" class="btn btn-small btn-outline-primary btn-2" onclick="select_all();return false;"><i class="fa fa-check-square"></i> <?php echo lng('SelectAll') ?> </a></li>
                 <li class="list-inline-item"><a href="#/unselect-all" class="btn btn-small btn-outline-primary btn-2" onclick="unselect_all();return false;"><i class="fa fa-window-close"></i> <?php echo lng('UnSelectAll') ?> </a></li>
                 <li class="list-inline-item"><a href="#/invert-all" class="btn btn-small btn-outline-primary btn-2" onclick="invert_all();return false;"><i class="fa fa-th-list"></i> <?php echo lng('InvertSelection') ?> </a></li>
+                <li class="list-inline-item"><input type="submit" class="hidden" name="download" id="a-download" value="Download" onclick="return confirm('<?php echo lng('Download selected files and folders?'); ?>')">
```
Comment (ner00) [inline tinyfilemanager.php:2312]: `Download selected files and folders?`
Does it work for folders though?

File: tinyfilemanager.php [hunk 2]
```diff
@@ -1053,6 +1068,75 @@ function get_file_path () {
...
+
+        foreach ($files as $f) {
+            if ($f != '') {
+                $new_path = $path . '/' . fm_clean_path($f); // Sanitize the file path
+
+                if (is_file($new_path)) {
+                    // Add the file to the ZIP archive
+                    $zip->addFile($new_path, basename($new_path));
+                } else {
+                    $errors++;
```
Comment (ner00) [inline tinyfilemanager.php:1107]: It clearly does not work with folders, so prompting `Download selected files and folders?` is misleading.

Comment (prasathmani) [reply tinyfilemanager.php:1107]: @vadasziattila can you add folder as well.

Comment (ner00) [reply tinyfilemanager.php:1107]: I think here is a good opportunity to make good use of the included `FM_Zipper` class.
Just a suggestion, but this would work okay:
```php
// Mass downloading
if (isset($_POST['group'], $_POST['download'], $_POST['token']) && !FM_READONLY) {

    // Verify token to ensure it's valid
    if(!verifyToken($_POST['token'])) {
        fm_set_msg(lng("Invalid Token."), 'error');
        exit;
    }

    $path = FM_ROOT_PATH;
    if (FM_PATH != '') {
        $path .= '/' . FM_PATH;
    }

    $files = $_POST['file']; // List of selected files
    if (is_array($files) && count($files)) {
        // Create a new ZIP archive
        $zip = new FM_Zipper();
        $zip_filename = 'download_' . date('Y-m-d_H-i-s') . '.zip';
        $zip_filepath = sys_get_temp_dir() . '/' . $zip_filename;

        chdir($path);
        $sanitized_filepaths = array();
        foreach($files as $f){
            if ($f != '') {
                array_push($sanitized_filepaths, fm_clean_path($f)); // Sanitize the file path
            }
        }
        $res = $zip->create($zip_filepath, $sanitized_filepaths);

        if ($res && file_exists($zip_filepath)) {
            // Serve the ZIP file for download
            header('Content-Type: application/zip');
            header('Content-Disposition: attachment; filename="' . $zip_filename . '"');
            header('Content-Length: ' . filesize($zip_filepath));
            readfile($zip_filepath);
            // Remove the ZIP file from the temporary directory after download
            unlink($zip_filepath);
            exit;
        } else {
            fm_set_msg(lng('Error creating ZIP file'), 'error');
        }
    } else {
        fm_set_msg(lng('Nothing selected'), 'alert');
    }

    $FM_PATH = FM_PATH;
    fm_redirect(FM_SELF_URL . '?p=' . urlencode($FM_PATH));
}
```

**Comment by prasathmani** [comment]
PR #1244
